spring.application.name=PortfolioService

spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.fail-fast=true


#
#server.port=${SERVER_PORT:8080}
#
#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portfolioDB}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#
#
#spring.servlet.multipart.max-file-size=10MB
#Spring.servlet.multipart.max-request-size=10MB
#
#aws.region=ap-south-1
#aws.s3.bucket=switchboard-commonbucket
#aws.accessKeyId=${AWS_ACCESS_KEY}
#aws.secretKey=${AWS_SECRET_KEY}
#
## Swagger/OpenAPI configuration
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.enabled=true
#swagger.dev-url=http://localhost:8080