spring.application.name=PortfolioService

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolioDB
spring.datasource.username=postgres
spring.datasource.password=Atul@2192


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



spring.servlet.multipart.max-file-size=10MB
Spring.servlet.multipart.max-request-size=10MB

aws.region=eu-north-1
aws.s3.bucket=switchboard-commonbucket
aws.accessKeyId=${AWS-ACCESS-KEY-ID}
aws.secretKey=${AWS-SECRET-KEY}